import { StyleSheet } from 'react-native';
import { COLORS, fontFamily, screenWidth } from '../../../../utils';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    scrollContent: {
        padding: 16,
        paddingBottom: 40,
    },
    queryCard: {
        backgroundColor: COLORS.white,
        borderRadius: 24,
        padding: 20,
        marginBottom: 16,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.1,
        shadowRadius: 16,
        elevation: 6,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    studentInfo: {
        flex: 1,
    },
    imageContainer: {
        width: 48,
        height: 48,
        borderRadius: 14,
        backgroundColor: '#F1F5F9',
        overflow: 'hidden',
    },
    studentAvatar: {
        width: '100%',
        height: '100%',
    },
    studentName: {
        fontSize: 15,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
    },
    studentClass: {
        fontSize: 11,
        color: '#64748B',
        fontFamily: fontFamily.Poppins.SemiBold,
    },
    subjectBadge: {
        backgroundColor: COLORS.primary + '15',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    subjectText: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Bold,
        color: COLORS.primary,
    },
    messageBox: {
        backgroundColor: '#F8FAFC',
        padding: 16,
        borderRadius: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#F1F5F9',
    },
    messageText: {
        fontSize: 14,
        color: '#475569',
        fontFamily: fontFamily.Poppins.Regular,
        lineHeight: 22,
    },
    // 🏛️ TEACHER REPLY STYLES
    teacherReplyBox: {
        backgroundColor: '#F0F7FF',
        padding: 16,
        borderRadius: 16,
        marginBottom: 16,
        borderLeftWidth: 4,
        borderLeftColor: COLORS.primary,
    },
    replyHeader: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.primary,
        letterSpacing: 0.5,
    },
    replyText: {
        fontSize: 13,
        color: COLORS.secondary,
        fontFamily: fontFamily.Poppins.Medium,
        lineHeight: 20,
    },
    // ⚙️ FOOTER & ACTIONS
    cardFooter: {
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#F1F5F9',
    },
    resolvedContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    resolvedText: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Black,
        color: '#10B981',
        marginLeft: 6,
    },
    editActionBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#F8FAFC',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    editActionText: {
        color: COLORS.primary,
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Bold,
    },
    replyBtn: {
        backgroundColor: COLORS.primary,
        height: 48,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    replyBtnText: {
        color: COLORS.white,
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        letterSpacing: 0.5,
    },
    // 📊 HUB STYLES
    statsContainer: {
        flexDirection: 'row',
        backgroundColor: COLORS.white,
        borderRadius: 24,
        padding: 20,
        marginBottom: 20,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
    },
    statBox: {
        flex: 1,
        alignItems: 'center',
    },
    statVal: {
        fontSize: 22,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
    },
    statLab: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Bold,
        color: '#94A3B8',
        marginTop: 2,
    },
    filterSection: {
        marginBottom: 16,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        borderRadius: 18,
        paddingHorizontal: 18,
        height: 56,
        borderWidth: 1,
        borderColor: '#EEF2F6',
        marginBottom: 12,
    },
    searchInput: {
        flex: 1,
        marginLeft: 12,
        fontFamily: fontFamily.Poppins.Regular,
        fontSize: 14,
        color: COLORS.secondary,
    },
    tabsContainer: {
        flexDirection: 'row',
        gap: 12,
    },
    tab: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 12,
        backgroundColor: '#F1F5F9',
    },
    activeTab: {
        backgroundColor: COLORS.primary,
    },
    tabText: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Bold,
        color: '#64748B',
    },
    activeTabText: {
        color: COLORS.white,
    },
    // 🎭 MODAL
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.7)',
        justifyContent: 'center',
        padding: 20,
    },
    modalContent: {
        backgroundColor: COLORS.white,
        borderRadius: 30,
        padding: 24,
        elevation: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        marginBottom: 8,
    },
    originalMsg: {
        fontSize: 13,
        color: '#64748B',
        fontFamily: fontFamily.Poppins.Medium,
        fontStyle: 'italic',
        lineHeight: 20,
        marginBottom: 20,
        padding: 12,
        backgroundColor: '#F8FAFC',
        borderRadius: 12,
    },
    input: {
        backgroundColor: '#F8FAFC',
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        minHeight: 140,
        textAlignVertical: 'top',
        color: COLORS.secondary,
        fontSize: 15,
        fontFamily: fontFamily.Poppins.Regular,
    },
    submitBtn: {
        backgroundColor: COLORS.primary,
        height: 60,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 8,
    },
    submitText: {
        color: COLORS.white,
        fontFamily: fontFamily.Poppins.Black,
        fontSize: 16,
    },
    cancelBtn: {
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
    },
    cancelText: {
        color: '#64748B',
        fontFamily: fontFamily.Poppins.Bold,
    }
});
