import { StyleSheet } from 'react-native';
import { COLORS, width, fontFamily } from '../../../../utils';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        backgroundColor: COLORS.primary,
        paddingBottom: 30,
        paddingHorizontal: 24,
        borderBottomLeftRadius: 36,
        borderBottomRightRadius: 36,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
    },
    backButton: {
        width: 44,
        height: 44,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    addButton: {
        width: 44,
        height: 44,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
    },
    metaBadge: {
        backgroundColor: 'rgba(255,255,255,0.15)',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 12,
        alignSelf: 'center',
        marginTop: 10,
    },
    metaBadgeText: {
        fontSize: 9,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 1.5,
    },
    searchSection: {
        paddingHorizontal: 24,
        marginTop: 20
    },
    searchBar: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        paddingHorizontal: 16,
        borderRadius: 18,
        height: 56,
        borderWidth: 1,
        borderColor: '#F1F5F9',
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
    },
    searchInput: {
        flex: 1,
        fontSize: 13,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.secondary,
        marginLeft: 12,
        paddingVertical: 0,
    },
    filterList: {
        marginTop: 16,
    },
    filterContent: {
        paddingRight: 24,
        gap: 8,
    },
    filterChip: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 12,
        backgroundColor: COLORS.white,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    activeChip: {
        backgroundColor: COLORS.secondary,
        borderColor: COLORS.secondary,
    },
    chipText: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
    },
    activeChipText: {
        color: COLORS.white,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingTop: 20,
        paddingBottom: 120,
    },
    // 📊 HIGH-DENSITY DIRECTORY STYLES
    tableHeader: {
        flexDirection: 'row',
        paddingHorizontal: 24,
        paddingVertical: 12,
        backgroundColor: '#F8FAFC',
        borderBottomWidth: 1,
        borderColor: '#E2E8F0',
        marginTop: 20,
    },
    headerCol: {
        fontSize: 9,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 1,
    },
    tableRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingVertical: 14,
        backgroundColor: COLORS.white,
        borderBottomWidth: 1,
        borderColor: '#F1F5F9',
    },
    idCol: {
        width: '20%',
    },
    idText: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
    },
    nameCol: {
        width: '55%',
    },
    studentName: {
        fontSize: 13,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
    },
    classInfo: {
        fontSize: 9,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.gray,
        marginTop: -2,
    },
    statusCol: {
        width: '25%',
        alignItems: 'flex-end',
    },
    miniBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    miniBadgeText: {
        fontSize: 8,
        fontFamily: fontFamily.Poppins.Black,
    },
    // ✨ COMPACT FOOTER
    actionFooter: {
        position: 'absolute',
        bottom: 25,
        left: 24,
        right: 24,
        backgroundColor: 'rgba(255,255,255,0.9)',
        padding: 10,
        borderRadius: 24,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 15,
        elevation: 10,
    },
    mainButton: {
        flexDirection: 'row',
        backgroundColor: COLORS.primary,
        height: 56,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
    },
    mainButtonText: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
    },
    reorderBtn: {
        width: 56,
        height: 56,
        backgroundColor: COLORS.primary,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 15,
        elevation: 5,
    }
});
