import { StyleSheet } from 'react-native';
import { COLORS, width, fontFamily } from '../../../../utils';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        backgroundColor: COLORS.primary,
        paddingBottom: 30,
        paddingHorizontal: 24,
        borderBottomLeftRadius: 36,
        borderBottomRightRadius: 36,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
    },
    backButton: {
        width: 44,
        height: 44,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
    },
    // 👣 STEPPER STYLES
    stepperContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 20,
        gap: 0,
    },
    stepUnit: {
        alignItems: 'center',
    },
    stepIcon: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: 'rgba(255,255,255,0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    stepActive: {
        backgroundColor: COLORS.white,
        borderColor: COLORS.white,
    },
    stepLine: {
        width: 60,
        height: 2,
        backgroundColor: 'rgba(255,255,255,0.1)',
        marginHorizontal: 10,
        marginTop: -16,
    },
    lineActive: {
        backgroundColor: COLORS.white,
    },
    stepLabel: {
        fontSize: 8,
        fontFamily: fontFamily.Poppins.Black,
        color: 'rgba(255,255,255,0.4)',
        marginTop: 6,
        letterSpacing: 1.5,
    },
    labelActive: {
        color: COLORS.white,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingTop: 30,
        paddingBottom: 120,
    },
    // 🛠️ FORM SECTION STYLES
    formSection: {
        gap: 20,
    },
    inputGroup: {
        gap: 8,
    },
    inputLabel: {
        fontSize: 9,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 1.5,
        marginLeft: 4,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        paddingHorizontal: 16,
        borderRadius: 18,
        height: 56,
        borderWidth: 1,
        borderColor: COLORS.border,
        shadowColor: '#000',
        shadowOpacity: 0.02,
        shadowRadius: 5,
    },
    input: {
        flex: 1,
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Bold,
        color: COLORS.secondary,
        marginLeft: 12,
    },
    rowInputs: {
        flexDirection: 'row',
    },
    staticText: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.primary,
        marginLeft: 12,
    },
    guidanceBox: {
        flexDirection: 'row',
        backgroundColor: COLORS.secondary + '05',
        padding: 20,
        borderRadius: 24,
        gap: 16,
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: COLORS.secondary + '20',
    },
    guidanceText: {
        flex: 1,
        fontSize: 11,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.secondary,
        lineHeight: 18,
    },
    primaryAction: {
        flexDirection: 'row',
        backgroundColor: COLORS.secondary,
        height: 64,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
        marginTop: 10,
        shadowColor: COLORS.secondary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 15,
        elevation: 8,
    },
    primaryActionText: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
    },
    // 📊 ENTRY SECTION STYLES
    entrySection: {
        gap: 20,
    },
    testMetaCard: {
        flexDirection: 'row',
        backgroundColor: COLORS.secondary,
        padding: 24,
        borderRadius: 28,
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    metaLabel: {
        fontSize: 8,
        fontFamily: fontFamily.Poppins.Black,
        color: 'rgba(255,255,255,0.5)',
        letterSpacing: 2,
        marginBottom: 4,
    },
    metaTitle: {
        fontSize: 16,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
    },
    metaDivider: {
        width: 1,
        height: 30,
        backgroundColor: 'rgba(255,255,255,0.1)',
    },
    registryHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    registryTitle: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 2,
    },
    registryCount: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.primary,
    },
    studentEntryCard: {
        flexDirection: 'row',
        backgroundColor: COLORS.white,
        padding: 16,
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.02)',
    },
    studentStatic: {
        flex: 1,
    },
    studentName: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
    },
    studentRoll: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.gray,
        marginTop: 2,
    },
    scoreInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.background,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    scoreInput: {
        fontSize: 16,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.primary,
        width: 40,
        textAlign: 'center',
        padding: 0,
    },
    scoreDivider: {
        fontSize: 16,
        color: COLORS.gray,
        marginHorizontal: 4,
    },
    scoreMax: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.ExtraBold,
        color: COLORS.gray,
    },
    commitButton: {
        flexDirection: 'row',
        backgroundColor: COLORS.green,
        height: 64,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
        marginTop: 10,
        shadowColor: COLORS.green,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 15,
        elevation: 8,
    },
    commitText: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
    },
});
