import { StyleSheet } from 'react-native';
import { COLORS, width, fontFamily } from '../../../../utils';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        backgroundColor: COLORS.primary,
        paddingBottom: 30,
        paddingHorizontal: 24,
        borderBottomLeftRadius: 36,
        borderBottomRightRadius: 36,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        marginTop: 40
    },
    backButton: {
        width: 44,
        height: 44,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
    },
    metaBadgeRow: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 20,
    },
    metaBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: COLORS.white,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 14,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 5,
    },
    metaBadgeText: {
        fontSize: 9,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.primary,
        letterSpacing: 1,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingTop: 30,
        paddingBottom: 150,
    },
    formCard: {
        backgroundColor: COLORS.white,
        borderRadius: 28,
        padding: 24,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 15,
        elevation: 5,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.02)',
    },
    inputGroup: {
        gap: 10,
    },
    inputLabel: {
        fontSize: 9,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 1.5,
    },
    titleInput: {
        fontSize: 16,
        fontFamily: fontFamily.Poppins.ExtraBold,
        color: COLORS.secondary,
        padding: 0,
    },
    divider: {
        height: 1,
        backgroundColor: COLORS.border,
        marginVertical: 20,
        opacity: 0.5,
    },
    descInput: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.secondary,
        minHeight: 120,
        padding: 0,
    },
    // ⏱️ DEADLINE STYLES
    deadlineRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        padding: 16,
        borderRadius: 22,
        marginTop: 20,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    deadlineIconBox: {
        width: 44,
        height: 44,
        backgroundColor: COLORS.secondary + '10',
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    deadlineInfo: {
        flex: 1,
    },
    deadlineLabel: {
        fontSize: 8,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 1.5,
    },
    deadlineValue: {
        fontSize: 13,
        fontFamily: fontFamily.Poppins.ExtraBold,
        color: COLORS.secondary,
        marginTop: 2,
    },
    // ⚠️ PRIORITY CARD
    priorityCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        padding: 20,
        borderRadius: 24,
        marginTop: 16,
        borderWidth: 1,
        borderColor: COLORS.border,
        gap: 16,
    },
    urgentActive: {
        backgroundColor: COLORS.secondary,
        borderColor: COLORS.secondary,
    },
    priorityTextContainer: {
        flex: 1,
    },
    priorityTitle: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        letterSpacing: 1,
    },
    priorityDesc: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.gray,
        marginTop: 2,
    },
    infoBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginTop: 24,
        paddingHorizontal: 8,
    },
    infoText: {
        flex: 1,
        fontSize: 10,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.gray,
        lineHeight: 16,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 24,
        right: 24,
    },
    deployButton: {
        flexDirection: 'row',
        backgroundColor: COLORS.primary,
        height: 64,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 10,
    },
    deployText: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
    },
});
