import { StyleSheet } from 'react-native';
import { COLORS, fontFamily, METRICES } from '../../../../utils';

export const styles = StyleSheet.create({
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 20,
    },
    sectionHeader: {
        marginBottom: 15,
        paddingHorizontal: 5,
    },
    sectionTitle: {
        fontSize: 11,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        letterSpacing: 2,
    },
    formCard: {
        backgroundColor: COLORS.white,
        borderRadius: 24,
        padding: 24,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 5,
    },
    dateRangeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    dateSelector: {
        flex: 1,
    },
    dateConnector: {
        paddingHorizontal: 10,
        paddingTop: 20,
    },
    inputLabel: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        marginBottom: 8,
        letterSpacing: 1,
    },
    dateDisplay: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: COLORS.background,
        padding: 12,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: COLORS.gray + '15',
    },
    dateText: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Bold,
        color: COLORS.primary,
    },
    typeSwitcher: {
        flexDirection: 'row',
        backgroundColor: COLORS.background,
        borderRadius: 14,
        padding: 5,
    },
    typeBtn: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        borderRadius: 10,
    },
    typeActive: {
        backgroundColor: COLORS.white,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    typeText: {
        fontSize: 11,
        fontFamily: fontFamily.Poppins.Bold,
        color: COLORS.gray,
    },
    typeActiveText: {
        color: COLORS.primary,
    },
    reasonInput: {
        backgroundColor: COLORS.background,
        borderRadius: 14,
        padding: 15,
        minHeight: 100,
        textAlignVertical: 'top',
        fontSize: 13,
        fontFamily: fontFamily.Poppins.Medium,
        color: COLORS.secondary,
        borderWidth: 1,
        borderColor: COLORS.gray + '15',
    },
    divider: {
        height: 1,
        backgroundColor: COLORS.gray + '10',
        marginVertical: 20,
    },
    inputGroup: {
        gap: 8,
    },
    submitBtn: {
        backgroundColor: COLORS.primary,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        paddingVertical: 16,
        borderRadius: 16,
        marginTop: 24,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    submitText: {
        fontSize: 13,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 1,
    },
    historyContainer: {
        gap: 15,
    },
    historyCard: {
        backgroundColor: COLORS.white,
        borderRadius: 20,
        padding: 15,
        borderWidth: 1,
        borderColor: COLORS.gray + '10',
    },
    historyMain: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    historyInfo: {
        flex: 1,
        marginRight: 10,
    },
    historyDates: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        marginBottom: 4,
    },
    historyReason: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Medium,
        color: COLORS.gray,
    },
    statusBadge: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 10,
    },
    statusText: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
    },
    historyFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        borderTopWidth: 1,
        borderTopColor: COLORS.gray + '05',
        paddingTop: 12,
    },
    historyTime: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Bold,
        color: COLORS.gray + '80',
    },
    dot: {
        width: 3,
        height: 3,
        borderRadius: 1.5,
        backgroundColor: COLORS.gray + '30',
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 40,
        backgroundColor: COLORS.gray + '05',
        borderRadius: 24,
        borderStyle: 'dashed',
        borderWidth: 1,
        borderColor: COLORS.gray + '20',
    },
    emptyText: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray + '50',
        marginTop: 10,
        letterSpacing: 1,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: COLORS.white,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        paddingBottom: 40,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.gray + '10',
    },
    modalTitle: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        letterSpacing: 1,
    },
    calendarWrapper: {
        padding: 10,
    },
});
