import { StyleSheet } from 'react-native';
import { COLORS, screenWidth, screenHeight, width, fontFamily } from '../../../../utils';


export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        paddingBottom: 40,
        paddingHorizontal: 24,
        borderBottomLeftRadius: 36,
        borderBottomRightRadius: 36,
        backgroundColor: COLORS.primary,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        paddingTop: 50, // Top inset for status bar
    },
    backButton: {
        width: 44,
        height: 44,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
        textTransform: 'uppercase',
    },
    classInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: 'rgba(255,255,255,0.95)',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 14,
        alignSelf: 'center',
        marginTop: 15,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
    },
    selectedClassText: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.primary,
        letterSpacing: 1.5,
    },
    // 📊 TELEMETRY AXIS STYLES
    telemetryAxis: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        marginTop: 20,
        justifyContent: 'space-between',
        gap: 8,
        zIndex: 10,
    },
    telemetryBox: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        backgroundColor: COLORS.white,
        paddingVertical: 16,
        paddingHorizontal: 4,
        borderRadius: 15,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.08,
        shadowRadius: 20,
        elevation: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.8)',
    },
    iconContainer: {
        width: 36,
        height: 36,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 4,
    },
    telemetryValue: {
        fontSize: 16,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        textAlign: 'center',
    },
    telemetryLabel: {
        fontSize: 8,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 1,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingTop: 50,
        paddingBottom: 150,
    },
    actionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
        gap: 12,
    },
    searchBox: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        paddingHorizontal: 18,
        borderRadius: 20,
        height: 52,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.05)',
        shadowColor: '#000',
        shadowOpacity: 0.02,
        shadowRadius: 5,
    },
    searchInput: {
        flex: 1,
        fontSize: 13,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.secondary,
        marginLeft: 10,
    },
    bulkButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: COLORS.white,
        paddingHorizontal: 16,
        height: 52,
        borderRadius: 20,
        borderWidth: 1.5,
        borderColor: COLORS.primary,
    },
    //  studentBadgeText: {
    //     fontSize: 10,
    //     fontFamily: fontFamily.Poppins.Black,
    //     color: COLORS.primary,
    // },
    // 📝 STUDENT CARD STYLES
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
        paddingHorizontal: 4,
    },
    sectionTitle: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 1.5,
        textTransform: 'uppercase',
    },
    badge: {
        backgroundColor: COLORS.primary + '15',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 10,
    },
    badgeText: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.primary,
    },
    studentCard: {
        flexDirection: 'row',
        backgroundColor: COLORS.white,
        padding: 12,
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.02)',
        shadowColor: '#000',
        shadowOpacity: 0.03,
        shadowRadius: 12,
        elevation: 2,
    },
    cardMain: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    studentAvatar: {
        width: '100%',
        height: '100%',
        borderRadius: 14,
    },
    imageContainer: {
        width: 48,
        height: 48,
        borderRadius: 14,
        backgroundColor: '#F1F5F9',
        marginRight: 16,
        overflow: 'hidden',
        borderWidth: 1.5,
        borderColor: '#F8FAFC',
    },
    cardStudentName: {
        fontSize: 13,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        letterSpacing: -0.2,
    },
    studentRoll: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.gray,
        marginTop: 2,
    },
    toggleGroup: {
        flexDirection: 'row',
        gap: 10,
    },
    paPill: {
        width: 42,
        height: 42,
        borderRadius: 15,
        backgroundColor: '#F1F5F9',
        justifyContent: 'center',
        alignItems: 'center',
    },
    paText: {
        fontSize: 15,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
    },
    activeText: {
        color: COLORS.white,
    },
    absoluteFooter: {
        position: 'absolute',
        bottom: 95,
        left: 24,
        right: 24,
    },
    commitButton: {
        flexDirection: 'row',
        backgroundColor: COLORS.secondary,
        height: 64,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
        shadowColor: COLORS.secondary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
    },
    commitText: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
    },
    // 🗓️ CALENDAR SELECTOR STYLES
    datePickerBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: '#fff',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 14,
        marginTop: 15,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        shadowColor: COLORS.secondary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.08,
        shadowRadius: 20,
        elevation: 3,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 60,
        paddingHorizontal: 40,
        marginBottom: 60
    },
    emptyIconContainer: {
        width: 100,
        height: 100,
        borderRadius: 40,
        backgroundColor: COLORS.white,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 15,
        elevation: 5,
    },
    emptyTitle: {
        fontSize: 18,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        letterSpacing: 0.5,
    },
    emptySubtitle: {
        fontSize: 13,
        fontFamily: fontFamily.Poppins.Medium,
        color: COLORS.gray,
        textAlign: 'center',
        marginTop: 8,
        lineHeight: 20,
    },
    resetButton: {
        marginTop: 24,
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 14,
        backgroundColor: COLORS.primary + '10',
    },
    resetButtonText: {
        fontSize: 13,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.primary,
    },
    dateBadgeText: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.black,
        letterSpacing: 1.5,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: COLORS.white,
        borderTopLeftRadius: 40,
        borderTopRightRadius: 40,
        padding: 24,
        paddingBottom: 80,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
        paddingHorizontal: 8,
    },
    modalTitle: {
        fontSize: 16,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        letterSpacing: 2,
    },
    calendarWrapper: {
        borderRadius: 24,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.05)',
    },
    // ✨ STATUS ORBITAL STYLES
    statusIconCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    // 📊 HIGH-DENSITY TABLE STYLES
    tableHeader: {
        flexDirection: 'row',
        paddingHorizontal: 24,
        paddingVertical: 12,
        backgroundColor: '#F8FAFC',
        borderBottomWidth: 1,
        borderColor: '#E2E8F0',
    },
    headerCol: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 1,
    },
    tableRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingVertical: 14,
        backgroundColor: COLORS.white,
        borderBottomWidth: 1,
        borderColor: '#F1F5F9',
    },
    rollCol: {
        width: '15%',
    },
    rollText: {
        fontSize: 13,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
    },
    nameCol: {
        width: '45%',
    },
    studentName: {
        fontSize: 13,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
    },
    studentId: {
        fontSize: 9,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.gray,
        marginTop: -2,
    },
    actionCol: {
        width: '40%',
        alignItems: 'flex-end',
    },
    statusGroup: {
        flexDirection: 'row',
        gap: 6,
    },
    statusBtn: {
        width: 32,
        height: 32,
        borderRadius: 10,
        backgroundColor: '#F1F5F9',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    statusBtnText: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
    },
    btnP: {
        backgroundColor: COLORS.green,
        borderColor: COLORS.green,
    },
    btnA: {
        backgroundColor: COLORS.red,
        borderColor: COLORS.red,
    },
    btnL: {
        backgroundColor: COLORS.orange || '#F59E0B',
        borderColor: COLORS.orange || '#F59E0B',
    },
    activeBtnText: {
        color: COLORS.white,
    },
    // ✨ COMPACT FOOTER
    footer: {
        marginTop: 30,
        paddingHorizontal: 24,
        paddingBottom: 40,
    },
    commitBtn: {
        height: 56,
        borderRadius: 18,
    },
    // ⚡ QUICK ACTIONS STYLES
    quickActionsRow: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        marginTop: 15,
        gap: 10,
    },
    markAllBtn: {
        flex: 2,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.secondary,
        paddingVertical: 12,
        borderRadius: 14,
        gap: 8,
        shadowColor: COLORS.secondary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    markAllText: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 1,
    },
    clearAllBtn: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.white,
        paddingVertical: 12,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: COLORS.gray + '30',
    },
    clearAllText: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 1,
    },
});
