export const INDIAN_STATES_AND_UTS = [
  "Uttar Pradesh", // Default selection for SDM Public School
  "Delhi (NCT)",
  "Uttarakhand",
  "Haryana",
  "Bihar",
  "Rajasthan",
  "Madhya Pradesh",
  "Punjab",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Chandigarh",
  "Ladakh",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Lakshadweep",
  "Puducherry",
  "Other"
] as const;

export const DEFAULT_STATE = "Uttar Pradesh";
