import { StyleSheet } from 'react-native';
import { COLORS, width, fontFamily } from '../../../../utils';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        backgroundColor: COLORS.primary,
        paddingBottom: 30,
        paddingHorizontal: 24,
        borderBottomLeftRadius: 36,
        borderBottomRightRadius: 36,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
    },
    backButton: {
        width: 44,
        height: 44,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
    },
    targetSwitcher: {
        flexDirection: 'row',
        backgroundColor: 'rgba(255,255,255,0.1)',
        padding: 6,
        borderRadius: 18,
        marginTop: 12,
    },
    targetBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 12,
        borderRadius: 14,
    },
    targetActive: {
        backgroundColor: COLORS.white,
    },
    targetText: {
        fontSize: 9,
        fontFamily: fontFamily.Poppins.Black,
        color: 'rgba(255,255,255,0.6)',
        letterSpacing: 1,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingTop: 30,
        paddingBottom: 150,
    },
    sectionTitle: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 2,
        marginBottom: 16,
    },
    categoryRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginBottom: 30,
    },
    categoryPill: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 12,
        backgroundColor: COLORS.white,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    categoryActive: {
        backgroundColor: COLORS.secondary,
        borderColor: COLORS.secondary,
    },
    categoryText: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 1,
    },
    categoryActiveText: {
        color: COLORS.white,
    },
    formCard: {
        backgroundColor: COLORS.white,
        borderRadius: 28,
        padding: 24,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 15,
        elevation: 5,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.02)',
    },
    inputGroup: {
        gap: 10,
    },
    inputLabel: {
        fontSize: 9,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 1.5,
    },
    titleInput: {
        fontSize: 16,
        fontFamily: fontFamily.Poppins.ExtraBold,
        color: COLORS.secondary,
        padding: 0,
    },
    divider: {
        height: 1,
        backgroundColor: COLORS.border,
        marginVertical: 20,
        opacity: 0.5,
    },
    contentInput: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.secondary,
        minHeight: 120,
        padding: 0,
    },
    guaranteeBox: {
        flexDirection: 'row',
        backgroundColor: COLORS.secondary + '05',
        padding: 20,
        borderRadius: 24,
        gap: 16,
        marginTop: 24,
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: COLORS.secondary + '20',
    },
    guaranteeText: {
        flex: 1,
        fontSize: 11,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.secondary,
        lineHeight: 18,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 24,
        right: 24,
    },
    emitButton: {
        flexDirection: 'row',
        backgroundColor: COLORS.secondary,
        height: 64,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
        shadowColor: COLORS.secondary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 10,
    },
    emitText: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
    },
    // --- 📥 NOTICE LIST STYLES ---
    mainContent: {
        paddingHorizontal: 24,
        paddingTop: 20,
    },
    summaryCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.1)',
        padding: 16,
        borderRadius: 18,
        marginTop: 15,
        gap: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    announcementIcon: {
        width: 44,
        height: 44,
        backgroundColor: COLORS.white,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    summaryText: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 1.5,
    },
    noticeCard: {
        backgroundColor: COLORS.white,
        borderRadius: 24,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.03)',
        shadowColor: '#000',
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 3,
    },
    noticeHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    tagBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    noticeTag: {
        fontSize: 8,
        fontFamily: fontFamily.Poppins.Black,
        letterSpacing: 1,
    },
    noticeDate: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: COLORS.gray,
    },
    noticeTitle: {
        fontSize: 15,
        fontFamily: fontFamily.Poppins.Bold,
        color: COLORS.secondary,
        marginBottom: 8,
    },
    noticePreview: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Medium,
        color: COLORS.gray,
        lineHeight: 18,
    },
    readMoreRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        marginTop: 12,
        gap: 4,
    },
    readMoreText: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.primary,
        letterSpacing: 0.5,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 100,
        gap: 16,
    },
    emptyTitle: {
        fontSize: 18,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
    },
    emptyDesc: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Medium,
        color: COLORS.gray,
        textAlign: 'center',
        paddingHorizontal: 40,
    },
    fab: {
        position: 'absolute',
        bottom: 30,
        right: 24,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
        elevation: 8,
    }
});
