import { StyleSheet } from 'react-native';
import { COLORS, screenWidth, screenHeight, width, fontFamily } from '../../../../utils';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingBottom: 100,
    },
    header: {
        paddingBottom: 40,
        paddingHorizontal: 24,
        borderBottomLeftRadius: 40,
        borderBottomRightRadius: 40,
        backgroundColor: COLORS.primary,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
    },
    backButton: {
        width: 44,
        height: 44,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 2,
        textTransform: 'uppercase',
    },
    headerSubtitle: {
        fontSize: 11,
        fontFamily: fontFamily.Poppins.SemiBold,
        color: 'rgba(255,255,255,0.9)',
        alignSelf: 'center',
        marginTop: 20,
        letterSpacing: 1.2,
    },
    selectorCard: {
        backgroundColor: COLORS.white,
        borderRadius: 24,
        padding: 20,
        marginBottom: 32,
        borderWidth: 1,
        borderColor: COLORS.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
    },
    selectorRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    selectionBox: {
        flex: 1,
        alignItems: 'center',
    },
    selectionLabel: {
        fontSize: 8,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 2,
        marginBottom: 4,
    },
    selectionValue: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.primary,
        letterSpacing: 0.5,
    },
    divider: {
        width: 1,
        height: '60%',
        backgroundColor: COLORS.border,
    },
    listHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 10,
        paddingHorizontal: 4,

    },
    listTitle: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        letterSpacing: 3,
        fontStyle: 'italic',
    },
    countText: {
        fontSize: 8,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        letterSpacing: 1.5,
    },
    studentCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        borderRadius: 20,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    studentAvatar: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: COLORS.background,
        marginRight: 16,
    },
    studentInfo: {
        flex: 1,
    },
    studentName: {
        fontSize: 16,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        letterSpacing: -0.5,
    },
    studentRoll: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Bold,
        color: COLORS.gray,
        marginTop: 2,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.background,
        borderRadius: 12,
        paddingHorizontal: 12,
        height: 48,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    markInput: {
        fontSize: 18,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.primary,
        width: 40,
        textAlign: 'center',
    },
    maxValue: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.gray,
        marginLeft: 4,
    },
    footerHost: {
        padding: 24,
        paddingBottom: 40,
        backgroundColor: COLORS.white,
        borderTopWidth: 1,
        borderTopColor: COLORS.border,
    },
    commitButton: {
        height: 60,
        backgroundColor: COLORS.primary,
        borderRadius: 18,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 24,
        marginBottom: 10,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 8,
    },
    commitText: {
        fontSize: 11,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        letterSpacing: 3,
        marginRight: 12,
        fontStyle: 'italic',
    },
    // 📚 TEST LIST STYLES
    testCard: {
        backgroundColor: COLORS.white,
        borderRadius: 24,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.03)',
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 15,
        elevation: 3,
    },
    testHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    testBadge: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 10,
    },
    testBadgeText: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        letterSpacing: 1,
    },
    testDate: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Bold,
        color: COLORS.gray,
    },
    testTitle: {
        fontSize: 18,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        letterSpacing: -0.5,
    },
    testMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        gap: 12,
    },
    metaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    metaText: {
        fontSize: 11,
        fontFamily: fontFamily.Poppins.Bold,
        color: COLORS.gray,
    },
    fab: {
        position: 'absolute',
        bottom: 30,
        right: 24,
        backgroundColor: COLORS.primary,
        width: 56,
        height: 56,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: COLORS.primary,
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 8,
    },
});
