import { StyleSheet } from 'react-native';
import { COLORS, screenWidth, screenHeight, fontFamily } from '../../../../utils';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    headerGradient: {
        paddingTop: 30,
        paddingBottom: 40,
        paddingHorizontal: 24,
        borderBottomLeftRadius: 40,
        borderBottomRightRadius: 40,
    },
    headerNav: {
        marginBottom: 20,
    },
    headerTitle: {
        fontSize: 28,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
        marginBottom: 24,
    },
    summaryCard: {
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 24,
        padding: 24,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        marginTop: 20,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    summaryLabel: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Bold,
        color: 'rgba(255,255,255,0.7)',
        letterSpacing: 1,
    },
    overallValue: {
        fontSize: 48,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.white,
    },
    medalBox: {
        width: 70,
        height: 70,
        backgroundColor: COLORS.white,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
    },
    mainContent: {
        paddingHorizontal: 20,
        paddingTop: 10,
    },
    tabScrollContainer: {
        marginBottom: 20,
        marginHorizontal: -20,
        paddingLeft: 20,
    },
    tabContainer: {
        flexDirection: 'row',
    },
    tabItem: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: COLORS.white,
        marginRight: 12,
        borderWidth: 1,
        borderColor: '#F1F5F9',
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    activeTabItem: {
        backgroundColor: COLORS.primary,
        borderColor: COLORS.primary,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    tabText: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Bold,
        color: '#64748B',
    },
    activeTabText: {
        color: COLORS.white,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 14,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
        marginLeft: 10,
        letterSpacing: 0.5,
    },
    chartSection: {
        backgroundColor: COLORS.white,
        borderRadius: 24,
        padding: 20,
        marginBottom: 25,
        shadowColor: '#6366F1',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.05,
        shadowRadius: 15,
        elevation: 5,
    },
    chartContainer: {
        height: 160,
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-around',
        paddingTop: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
    },
    chartBarWrapper: {
        alignItems: 'center',
        width: (screenWidth - 80) / 5,
    },
    chartBar: {
        width: 25,
        borderRadius: 8,
    },
    chartLabel: {
        fontSize: 9,
        fontFamily: fontFamily.Poppins.Bold,
        color: '#64748B',
        marginTop: 10,
        marginBottom: 5,
    },
    subjectCard: {
        backgroundColor: COLORS.white,
        borderRadius: 24,
        padding: 20,
        marginBottom: 16,
        shadowColor: '#6366F1',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 2,
    },
    subjectHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    subjectName: {
        fontSize: 15,
        fontFamily: fontFamily.Poppins.ExtraBold,
        color: COLORS.secondary,
    },
    marksText: {
        fontSize: 15,
        fontFamily: fontFamily.Poppins.Black,
        color: COLORS.secondary,
    },
    progressTrack: {
        height: 8,
        backgroundColor: '#F1F5F9',
        borderRadius: 4,
        marginBottom: 8,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        borderRadius: 4,
    },
    percentageText: {
        fontSize: 12,
        fontFamily: fontFamily.Poppins.Bold,
        color: '#64748B',
    },
    miniIconBox: {
        width: 32,
        height: 32,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    gradeText: {
        fontSize: 11,
        fontFamily: fontFamily.Poppins.Bold,
        color: COLORS.gray,
        marginTop: -3,
    },
    statusTag: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Black,
        letterSpacing: 0.5,
    },
    // 💳 FIGMA IN-BODY RESULTS CARD
    figmaResultsCard: {
        marginHorizontal: 20,
        marginTop: 16,
        borderRadius: 24,
        overflow: 'hidden',
        shadowColor: '#6C63FF',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.08,
        shadowRadius: 20,
        elevation: 6,
    },
    figmaResultsGradient: {
        padding: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    figmaResultsLabel: {
        fontSize: 10,
        fontFamily: fontFamily.Poppins.Bold,
        color: 'rgba(255,255,255,0.7)',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    figmaResultsValue: {
        fontSize: 38,
        fontFamily: fontFamily.Poppins.Black,
        color: '#FFFFFF',
        marginTop: 4,
    },
    figmaMedalBox: {
        width: 60,
        height: 60,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
        elevation: 3,
    },
});
